name: Buduj Testowy EXE

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Pobieranie kodu
      uses: actions/checkout@v4

    - name: Konfiguracja MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Kompilacja
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
        csc /out:TestowyProgram.exe Program.cs

    - name: Udostepnij plik
      uses: actions/upload-artifact@v4
      with:
        name: Paczka_Testowa
        path: TestowyProgram.exe
