name: Buduj EXE dla Windows

on: 
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Pobieranie kodu
      uses: actions/checkout@v4

    - name: Kompilacja programu C#
      run: csc /out:MojProgram.exe Program.cs

    - name: Udostepnij plik EXE
      uses: actions/upload-artifact@v4
      with:
        name: Program_Windows
        path: MojProgram.exe
