name: Buduj EXE

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Pobieranie kodu
      uses: actions/checkout@v4

    - name: Konfiguracja narzedzi MSBuild (Kompilator)
      uses: microsoft/setup-msbuild@v2

    - name: Kompilacja programu
      shell: cmd
      run: csc /out:MojProgram.exe Program.cs

    - name: Udostepnij gotowy plik
      uses: actions/upload-artifact@v4
      with:
        name: Program_Windows
        path: MojProgram.exe
